CREATE TABLE saved_recipes (saved_id UUID,
                            idDrink VARCHAR(20),
                                    strDrink VARCHAR(40),
                                             strGlass VARCHAR(20),
                                                      strIngredient1 VARCHAR(20),
                                                                     strIngredient2 VARCHAR(20),
                                                                                    strIngredient3 VARCHAR(20),
                                                                                                   strIngredient4 VARCHAR(20),
                                                                                                                  strIngredient5 VARCHAR(20),
                                                                                                                                 strIngredient6 VARCHAR(20),
                                                                                                                                                strIngredient7 VARCHAR(20),
                                                                                                                                                               strIngredient8 VARCHAR(20),
                                                                                                                                                                              strIngredient9 VARCHAR(20),
                                                                                                                                                                                             strIngredient10 VARCHAR(20),
                                                                                                                                                                                                             strIngredient11 VARCHAR(20),
                                                                                                                                                                                                                             strIngredient12 VARCHAR(20),
                                                                                                                                                                                                                                             strIngredient13 VARCHAR(20),
                                                                                                                                                                                                                                                             strIngredient14 VARCHAR(20),
                                                                                                                                                                                                                                                                             strIngredient15 VARCHAR(20),
                                                                                                                                                                                                                                                                                             strInstructions VARCHAR(255),
                                                                                                                                                                                                                                                                                                             strMeasure1 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                         strMeasure2 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                     strMeasure3 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                 strMeasure4 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                             strMeasure5 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                         strMeasure6 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                     strMeasure7 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                 strMeasure8 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                             strMeasure9 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                                         strMeasure10 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                                                      strMeasure11 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                   strMeasure12 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                strMeasure13 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             strMeasure14 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          strMeasure15 VARCHAR(20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       user_id UUID);


INSERT INTO saved_recipes (saved_id,idDrink,strDrink,strGlass,strIngredient1,strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strInstructions, strMeasure1, strMeasure2, strMeasure3, strMeasure4, strMeasure5, strMeasure6, strMeasure7, strMeasure8, strMeasure9, strMeasure10, strMeasure11, strMeasure12, strMeasure13, strMeasure14, strMeasure15, user_id)
VALUES (uuid_generate_v4,
        '100',
        'Not Another Word',
        'coupe',
        'Rye',
        'lemon Juice',
        'Aperol',
        'Cocchi Americano',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'Shake & Strain',
        '.75oz',
        '1oz',
        '.5oz',
        '3oz',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '5fd2ddc4-0013-43e8-a3e0-f9c11852467e');


INSERT INTO saved_recipes (saved_id,idDrink,strDrink,strGlass,strIngredient1,strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strInstructions, strMeasure1, strMeasure2, strMeasure3, strMeasure4, strMeasure5, strMeasure6, strMeasure7, strMeasure8, strMeasure9, strMeasure10, strMeasure11, strMeasure12, strMeasure13, strMeasure14, strMeasure15, user_id)
VALUES (uuid_generate_v4(),
        '110',
        'Last Word',
        'coupe',
        'Gin',
        'Lime Juice',
        'Green Chartreuese',
        'Luxardo',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'Shake & Strain',
        '1oz',
        '1.5oz',
        '2.5oz',
        '.25oz',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '5fd2ddc4-0013-43e8-a3e0-f9c11852467e');


INSERT INTO saved_recipes (saved_id,idDrink,strDrink,strGlass,strIngredient1,strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strInstructions, strMeasure1, strMeasure2, strMeasure3, strMeasure4, strMeasure5, strMeasure6, strMeasure7, strMeasure8, strMeasure9, strMeasure10, strMeasure11, strMeasure12, strMeasure13, strMeasure14, strMeasure15, user_id)
VALUES (uuid_generate_v4(),
        '100',
        'Not Another Word',
        'coupe',
        'Rye',
        'lemon Juice',
        'Aperol',
        'Cocchi Americano',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'Shake & Strain',
        '.75oz',
        '1oz',
        '.5oz',
        '3oz',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '5fd2ddc4-0013-43e8-a3e0-f9c11852467e');


INSERT INTO saved_recipes (saved_id,idDrink,strDrink,strGlass,strIngredient1,strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strInstructions, strMeasure1, strMeasure2, strMeasure3, strMeasure4, strMeasure5, strMeasure6, strMeasure7, strMeasure8, strMeasure9, strMeasure10, strMeasure11, strMeasure12, strMeasure13, strMeasure14, strMeasure15, user_id)
VALUES (uuid_generate_v4(),
        '20',
        'El Matador',
        'King Kube',
        'Tequila',
        'Lime Juice',
        'Ginger Syrup',
        'Ancho Reyes',
        'Cracked Pepper',
        'Grapefruit Twist',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'Shake & Strain over a big cube',
        '1',
        '1',
        '.5',
        '.5',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '5fd2ddc4-0013-43e8-a3e0-f9c11852467e');


INSERT INTO saved_recipes (saved_id,idDrink,strDrink,strGlass,strIngredient1,strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strInstructions, strMeasure1, strMeasure2, strMeasure3, strMeasure4, strMeasure5, strMeasure6, strMeasure7, strMeasure8, strMeasure9, strMeasure10, strMeasure11, strMeasure12, strMeasure13, strMeasure14, strMeasure15, user_id)
VALUES (uuid_generate_v4(),
        '200',
        'Indifference Cherished',
        'Couple',
        'Bourbon',
        'Amaro Nonino',
        'Cochi Americano',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'Stir',
        '60ml',
        '60mL',
        '60Ml',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '686abb99-a94a-47f1-aa12-22b24a41e2ee');


INSERT INTO saved_recipes (saved_id,idDrink,strDrink,strGlass,strIngredient1,strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strInstructions, strMeasure1, strMeasure2, strMeasure3, strMeasure4, strMeasure5, strMeasure6, strMeasure7, strMeasure8, strMeasure9, strMeasure10, strMeasure11, strMeasure12, strMeasure13, strMeasure14, strMeasure15, user_id)
VALUES (uuid_generate_v4(),
        '30',
        'Something Delicious',
        'Rocks',
        'Vodka',
        'St. Germain',
        'Lemon Juice',
        'Aperol',
        'Grapefruit Bitters',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'Shake & Strain over ice',
        '2',
        '1oz',
        '.5oz',
        '.5oz',
        null,
        null,
        null,
        null,
        null,
        null,
        'strip',
        null,
        null,
        null,
        null,
        '686abb99-a94a-47f1-aa12-22b24a41e2ee');